<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10528" started-at="2023-03-30T11:05:33Z" finished-at="2023-03-30T11:05:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10528" started-at="2023-03-30T11:05:33Z" finished-at="2023-03-30T11:05:44Z">
      <class name="reUsable_MyContactForm_Time_Assert.MyContactForm">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:reUsable_MyContactForm_Time_Assert.MyContactForm@20322d26]" name="openBrowser" is-config="true" duration-ms="7139" started-at="2023-03-30T16:35:33Z" finished-at="2023-03-30T16:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="toCheckForm()[pri:0, instance:reUsable_MyContactForm_Time_Assert.MyContactForm@20322d26]" name="toCheckForm" duration-ms="3351" started-at="2023-03-30T16:35:40Z" finished-at="2023-03-30T16:35:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Incorrect login, please try again.] but found [Incorrect login, please try again]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Incorrect login, please try again.] but found [Incorrect login, please try again]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at reUsable_MyContactForm_Time_Assert.MyContactForm.toCheckForm(MyContactForm.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toCheckForm -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:reUsable_MyContactForm_Time_Assert.MyContactForm@20322d26]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2023-03-30T16:35:44Z" finished-at="2023-03-30T16:35:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- reUsable_MyContactForm_Time_Assert.MyContactForm -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
